# Generated by Django 5.2.1 on 2025-07-13 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMBCChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustingTube', models.CharField(max_length=100)),
                ('cylinderBody', models.CharField(max_length=100)),
                ('pistonTrunnion', models.CharField(max_length=100)),
                ('plungerSpring', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BogieChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axleGuide', models.CharField(max_length=100)),
                ('bogieFrameCondition', models.CharField(max_length=100)),
                ('bolster', models.CharField(max_length=100)),
                ('bolsterSuspensionBracket', models.CharField(max_length=100)),
                ('lowerSpringSeat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BogieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bogieNo', models.CharField(max_length=100)),
                ('dateOfIOH', models.DateField()),
                ('deficitComponents', models.CharField(max_length=255)),
                ('incomingDivAndDate', models.CharField(max_length=100)),
                ('makerYearBuilt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WheelSpecificationFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axleBoxHousingBoreDia', models.CharField(blank=True, max_length=100)),
                ('bearingSeatDiameter', models.CharField(blank=True, max_length=100)),
                ('condemningDia', models.CharField(blank=True, max_length=100)),
                ('intermediateWWP', models.CharField(blank=True, max_length=100)),
                ('lastShopIssueSize', models.CharField(blank=True, max_length=100)),
                ('rollerBearingBoreDia', models.CharField(blank=True, max_length=100)),
                ('rollerBearingOuterDia', models.CharField(blank=True, max_length=100)),
                ('rollerBearingWidth', models.CharField(blank=True, max_length=100)),
                ('treadDiameterNew', models.CharField(blank=True, max_length=100)),
                ('variationSameAxle', models.CharField(blank=True, max_length=100)),
                ('variationSameBogie', models.CharField(blank=True, max_length=100)),
                ('variationSameCoach', models.CharField(blank=True, max_length=100)),
                ('wheelDiscWidth', models.CharField(blank=True, max_length=100)),
                ('wheelGauge', models.CharField(blank=True, max_length=100)),
                ('wheelProfile', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BogieForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=50, unique=True)),
                ('inspectionBy', models.CharField(max_length=100)),
                ('inspectionDate', models.DateField()),
                ('status', models.CharField(default='Saved', max_length=50)),
                ('bmbcChecksheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inspections.bmbcchecksheet')),
                ('bogieChecksheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inspections.bogiechecksheet')),
                ('bogieDetails', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inspections.bogiedetails')),
            ],
        ),
        migrations.CreateModel(
            name='WheelSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=50, unique=True)),
                ('submittedBy', models.CharField(max_length=100)),
                ('submittedDate', models.DateField()),
                ('fields', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inspections.wheelspecificationfields')),
            ],
        ),
    ]
